name: Bridgecrew1
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      steps:
      -uses: actions/checkout@v2
      -name: Run Bridgecrew1 
        id: Bridgecrew1
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api0.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          directory: terraform/
